# Generated by Django 5.0.3 on 2024-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Development', 'Development'), ('Testing', 'Testing'), ('HR', 'HR')]),
        ),
    ]
